version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:9.11.1
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - dependencies-cache-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}

      - run:
          name: install-awscli-and-dependencies
          command: |
            yarn --ignore-engines
            #./override.sh transports credentials connect

      - run:
          name: deploy-to-s3
          command: |
            if [ "${CIRCLE_BRANCH}" == "develop" ]; then
              yarn deploy-space
            fi
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              yarn deploy-production
            fi
            if [ "${CIRCLE_BRANCH}" == "test" ]; then
              yarn deploy-test
            fi

      - save_cache:
          key: dependencies-cache-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
